/**
 * ABDM Scan & Share — the counter QR.
 *
 * A patient opens the ABHA app, scans a QR at reception, and their KYC'd
 * profile is pushed to us. It removes typing and OTPs from registration
 * entirely, and NHA pushes it harder than any other ABHA feature.
 *
 * The QR is **not** generated by an ABDM API. It is a plain URL carrying two
 * parameters (Scan & Share spec §4.1):
 *
 *   https://phrsbx.abdm.gov.in/share-profile?hipid=<HIP ID>&counterid=<context>
 *
 * So the whole of the "generate" side is string building — which is why this
 * file has no network calls. The real work is the inbound callback that
 * arrives afterwards, server-side.
 *
 * What makes it fail in practice is the *identifiers*, not the QR: a wrong or
 * missing HIP ID produces a QR that scans fine and then dead-ends inside the
 * patient's ABHA app, with nothing on our side to show why. Hence the explicit
 * readiness check rather than rendering a QR regardless.
 */

import QRCode from 'qrcode';

/** Where the patient's PHR app resolves the share, per environment. */
const SHARE_HOSTS = {
  sandbox: 'https://phrsbx.abdm.gov.in/share-profile',
  production: 'https://phr.abdm.gov.in/share-profile',
} as const;

export type AbdmEnv = keyof typeof SHARE_HOSTS;

export interface ScanShareIdentity {
  /** ABDM's HIP ID for THIS clinic. Not the bridge/client id. */
  abdmHipId: string | null;
  /** Facility-defined context — which desk this QR belongs to. */
  abdmCounterCode: string | null;
  /** Shown for support; never part of the QR. */
  hfrFacilityId?: string | null;
}

export type ScanShareReadiness =
  | { ready: true; hipId: string; counterCode: string }
  | { ready: false; reason: string };

/**
 * Whether this clinic can produce a working QR yet.
 *
 * Separated from rendering so the UI can explain *what is missing* instead of
 * showing a broken QR. Registration is a multi-week operational process and a
 * clinic will sit in the not-ready state for a long time.
 */
export function checkScanShareReadiness(identity: ScanShareIdentity): ScanShareReadiness {
  const hipId = (identity.abdmHipId ?? '').trim();

  if (!hipId) {
    return {
      ready: false,
      reason: identity.hfrFacilityId
        ? 'This clinic is registered with HFR but its bridge is not linked yet, so ABDM has not issued a HIP ID. Complete "Software Linkage" on the HFR portal.'
        : 'This clinic is not registered with ABDM yet. Register the facility on the HFR portal, then link the bridge to get a HIP ID.',
    };
  }

  // The HIP ID for a facility's first bridge equals its HFR id; later bridges
  // get a '_1' suffix (FAQ v1.4 Q24). Both are valid, so validate the shape
  // loosely — rejecting a legitimate '_1' would be worse than accepting junk,
  // which ABDM rejects anyway.
  if (!/^IN[A-Za-z0-9]{10}(_\d+)?$/.test(hipId)) {
    return {
      ready: false,
      reason: `"${hipId}" does not look like a HIP ID. Expected 12 characters starting "IN", optionally with a bridge suffix such as _1.`,
    };
  }

  return {
    ready: true,
    hipId,
    // '1' matches the column default: a single-desk clinic never has to think
    // about counters.
    counterCode: (identity.abdmCounterCode ?? '').trim() || '1',
  };
}

/**
 * The URL encoded into the QR. Exported so it can be shown and copied.
 *
 * ############ BOTH SPELLINGS ARE DELIBERATE — DO NOT "TIDY" ################
 *
 * The Scan & Share spec §4.1 shows `?hipid=…&counterid=…` (lowercase). The
 * ABHA PHR app actually reads **`hipId` / `counterId`** (camelCase). Query
 * parameters are case-sensitive, so a spec-spelled QR loads the route and then
 * fails to resolve, rendering "Page not found" — confirmed against the sandbox
 * PHR on 2026-08-26, where the string "hipid" does not appear in the app bundle
 * at all while "hipId" does.
 *
 * We emit both. Unknown query parameters are ignored by whichever reader gets
 * it, and the failure mode of guessing wrong is a QR that a patient scans at a
 * counter and which silently dead-ends inside their app, with nothing on our
 * side to show why. Ugly URL, working QR.
 *
 * Collapse to one spelling only after confirming what the PRODUCTION app reads
 * — the sandbox app is not evidence for it.
 * ###########################################################################
 */
export function buildShareProfileUrl(
  hipId: string,
  counterCode: string,
  env: AbdmEnv = 'sandbox',
): string {
  const url = new URL(SHARE_HOSTS[env]);
  url.searchParams.set('hipId', hipId);
  url.searchParams.set('counterId', counterCode);
  url.searchParams.set('hipid', hipId);
  url.searchParams.set('counterid', counterCode);
  return url.toString();
}

/**
 * PNG data URI for the counter QR.
 *
 * Deliberately high error correction and a generous quiet zone: this is
 * printed once, taped to a desk, and then photographed at an angle under
 * fluorescent light for years. A QR that scans on the second attempt costs
 * more at a busy counter than the extra ink.
 */
export async function renderShareProfileQr(
  hipId: string,
  counterCode: string,
  env: AbdmEnv = 'sandbox',
): Promise<{ dataUrl: string; url: string }> {
  const url = buildShareProfileUrl(hipId, counterCode, env);
  const dataUrl = await QRCode.toDataURL(url, {
    errorCorrectionLevel: 'H',
    margin: 3,
    width: 512,
  });
  return { dataUrl, url };
}
